### ISSUE TITLE
chilloutandwatchsomecatgifs.com has expired

### ISSUE THREAD

**Issue by kumar303** [ibarlow/chilloutandwatchsomecatgifs#13]
I am so stressed right now!

At http://chilloutandwatchsomecatgifs.com/ I see:

![screenshot 2016-10-13 14 40 29](https://cloud.githubusercontent.com/assets/55398/19364247/06ebe11e-9153-11e6-973c-8b219c8f9ffe.png)

**Comment by turtlemaster19** [comment]
@ibarlow Where are you?

**Comment by turtlemaster19** [comment]
@ibarlow I went to ibarlow.github.io/chilloutandwatchsomecatgifs but even that points to the expired domain

**Comment by bwinton** [comment]
I'm not sure why, but apparently https://chilloutandwatchsomecatgifs.github.io/ works… ¯\_(ツ)_/¯

**Comment by turtlemaster19** [comment]
It works due to this repo: https://github.com/chilloutandwatchsomecatgifs/chilloutandwatchsomecatgifs.github.io

**Comment by bwinton** [comment]
Nope. That would be something only Ian could do, and I suspect he's got more important things taking up his time…

**Comment by UInt2048** [comment]
@bwinton Do you have write access? If so, I could make a PR with a link to the other repo until Ian comes back.

**Comment by bwinton** [comment]
I've already changed the Readme, and have contacted GitHub support to see if I can get access to the other repo…
